version: '3.7'
services:
  declaration-api-service:
    image: springapi-postgres
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - declaration-database
  declaration-database:
    image: postgres:latest
    restart: always
    ports:
      - 32769:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=declarationdb
